# Generated by Django 4.0.5 on 2022-06-28 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=120)),
                ('payment_range', models.IntegerField(choices=[(1, 'Low'), (2, 'Mid First'), (3, 'Mid Second'), (4, 'High')])),
                ('education', models.IntegerField(choices=[(1, 'Middle'), (2, 'High'), (3, 'Associate'), (4, 'Bachelor'), (5, 'Master'), (6, 'Phd')])),
                ('position_level', models.IntegerField(choices=[(1, 'Intern'), (2, 'Jr'), (3, 'Pl'), (4, 'Se'), (5, 'Lead')])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('payment_range', models.IntegerField(choices=[(1, 'Low'), (2, 'Mid First'), (3, 'Mid Second'), (4, 'High')])),
                ('education_req', models.IntegerField(choices=[(1, 'Middle'), (2, 'High'), (3, 'Associate'), (4, 'Bachelor'), (5, 'Master'), (6, 'Phd')])),
                ('position_level', models.IntegerField(choices=[(1, 'Intern'), (2, 'Jr'), (3, 'Pl'), (4, 'Se'), (5, 'Lead')])),
                ('candidacts', models.ManyToManyField(to='jobs.candidact')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
