# Generated by Django 4.0.5 on 2022-07-03 15:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_company", models.BooleanField(default=False)),
                ("is_candidate", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, null=True)),
                ("last_name", models.CharField(max_length=120, null=True)),
                (
                    "payment_range",
                    models.IntegerField(
                        choices=[
                            (1, "LOW (Up to 1000)"),
                            (2, "MID FIRST (1000~2000)"),
                            (3, "MID SECOND (2000~3000)"),
                            (4, "HIGH (More than 3000)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "education",
                    models.IntegerField(
                        choices=[
                            (1, "MIDDLE"),
                            (2, "HIGH"),
                            (3, "ASSOCIATE"),
                            (4, "BACHELOR"),
                            (5, "MASTER"),
                            (6, "PHD"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "position_level",
                    models.IntegerField(
                        choices=[
                            (1, "INTERN"),
                            (2, "JUNIOR"),
                            (3, "PLENO"),
                            (4, "SENIOR"),
                            (5, "LEAD"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("site", models.URLField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=125)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "payment_range",
                    models.IntegerField(
                        choices=[
                            (1, "LOW (Up to 1000)"),
                            (2, "MID FIRST (1000~2000)"),
                            (3, "MID SECOND (2000~3000)"),
                            (4, "HIGH (More than 3000)"),
                        ]
                    ),
                ),
                (
                    "education_req",
                    models.IntegerField(
                        choices=[
                            (1, "MIDDLE"),
                            (2, "HIGH"),
                            (3, "ASSOCIATE"),
                            (4, "BACHELOR"),
                            (5, "MASTER"),
                            (6, "PHD"),
                        ]
                    ),
                ),
                (
                    "position_level",
                    models.IntegerField(
                        choices=[
                            (1, "INTERN"),
                            (2, "JUNIOR"),
                            (3, "PLENO"),
                            (4, "SENIOR"),
                            (5, "LEAD"),
                        ]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobCandidated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_candidated", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.candidate",
                    ),
                ),
                (
                    "job_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.joboffer"
                    ),
                ),
            ],
        ),
    ]
