# Generated by Django 4.0.5 on 2022-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='candidacts',
            field=models.ManyToManyField(null=True, to='jobs.candidact'),
        ),
    ]
