# Generated by Django 4.0.5 on 2022-07-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobcandidated',
            constraint=models.UniqueConstraint(fields=('job_offer', 'candidate'), name='only apply once'),
        ),
    ]
