# Generated by Django 4.0.5 on 2022-06-28 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joboffer_candidacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='candidacts',
        ),
        migrations.AlterField(
            model_name='candidact',
            name='position_level',
            field=models.IntegerField(choices=[(1, 'Intern'), (2, 'Junior'), (3, 'Pleno'), (4, 'Senior'), (5, 'Lead')]),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='position_level',
            field=models.IntegerField(choices=[(1, 'Intern'), (2, 'Junior'), (3, 'Pleno'), (4, 'Senior'), (5, 'Lead')]),
        ),
        migrations.CreateModel(
            name='JobCandidacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.candidact')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.joboffer')),
            ],
        ),
    ]
