# Generated by Django 4.0.5 on 2022-07-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_jobcandidated_only apply once"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobCandidated",
            new_name="JobApplied",
        ),
    ]
