# Generated by Django 4.0.5 on 2022-06-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_joboffer_candidacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='remote', max_length=50),
            preserve_default=False,
        ),
    ]
