# Generated by Django 4.0.5 on 2022-07-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_jobcandidated_jobapplied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplied',
            old_name='date_candidated',
            new_name='date_applied',
        ),
    ]
