# Generated by Django 4.0.5 on 2022-06-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joboffer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
