# Generated by Django 4.0.5 on 2022-06-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidacted',
            name='candidact',
        ),
        migrations.AddField(
            model_name='jobcandidacted',
            name='candidact',
            field=models.ManyToManyField(to='jobs.candidact'),
        ),
    ]
