# Generated by Django 4.0.5 on 2022-06-28 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobcandidacted_candidact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidacted',
            old_name='candidact',
            new_name='candidacts',
        ),
    ]
