# Generated by Django 4.0.5 on 2022-06-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_candidact_jobcandidacted_candidacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidacted',
            name='candidacts',
        ),
        migrations.AddField(
            model_name='jobcandidacted',
            name='candidacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.candidact'),
        ),
    ]
