# Generated by Django 4.0.5 on 2022-06-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_jobcandidacted_candidacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidacted',
            name='candidacts',
        ),
        migrations.AddField(
            model_name='jobcandidacted',
            name='candidacts',
            field=models.ManyToManyField(to='jobs.candidact'),
        ),
    ]
