# Generated by Django 4.0.5 on 2022-06-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_jobcandidacted_candidacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcandidacted',
            old_name='candidacts',
            new_name='candidact',
        ),
    ]
